### PR TITLE
Create Shell Script and arrange other codes in their respective folders.

### PR DESCRIPTION
**Pull request by psycho-source**

### CODE REVIEW

**Comment by mukulgoyal793** [comment]
Can you please refactor your files into folders with correct names.

**Comment by psycho-source** [comment]
> Can you please refactor your files into folders with correct names.

I did exactly that! I am not sure if we want to have a common names for all files or it can be different.

**Comment by psycho-source** [comment]
> Can you please refactor your files into folders with correct names.

All files are in their correct folders now. you can check the commits.

**Comment by mukulgoyal793** [comment]
File names can be different but language folder should be unique. So, there should not be two folders for Kotlin language as it is right now in your changes.
Please review your code once more.

**Pull request merged**
